package Players

import Common.Action
import Common.PublicGameState
import Common.board.Coordinates
import Common.tile.GameTile


/**
 * Abstraction layer class denoting a player's API, to be used to represent a player connecting to the game and the
 * API expected from it. RandomSeed is used for testing.
 */
interface PlayerMechanism {
    val name: String //getName is generated by

    fun proposeBoard0(rows: Int, columns: Int): Array<Array<GameTile>>

    fun setupAndUpdateGoal(state: PublicGameState?, goal: Coordinates)

    fun takeTurn(state: PublicGameState): Action

    fun won(hasPlayerWon: Boolean)
}

